packages:
  - apps/*
  - packages/*

ignoredBuiltDependencies:
  - '@bundled-es-modules/glob'
  - '@parcel/watcher'
  - '@swc/core'
  - cpu-features
  - esbuild
  - protobufjs
  - sharp
  - ssh2
  - style-dictionary
  - unrs-resolver

onlyBuiltDependencies:
  - better-sqlite3
