name: Playwright Tests

on:
  push:

permissions:
  contents: read

jobs:
  pipeline:
    name: E2E pipeline
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/playwright:v1.59.1-noble

    steps:
      - uses: actions/checkout@v6
      - uses: pnpm/action-setup@v4
      - uses: actions/setup-node@v6
        with:
          node-version: 24
          cache: pnpm
      
      - run: pnpm install
      - run: pnpm build
      - run: pnpm test:e2e
